set_property SRC_FILE_INFO {cfile:D:/myhub/Side_Channel_Attack/chipwhisperer/fpga/Xor_Operation/Xor_Operation.srcs/constrs_1/imports/vivado/cw312_ss2.xdc rfile:../../../Xor_Operation.srcs/constrs_1/imports/vivado/cw312_ss2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN R1} [get_ports led1]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN V2} [get_ports led2]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {DRIVE 8 IOSTANDARD LVCMOS33 PACKAGE_PIN V5} [get_ports led3]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN D15} [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A13} [get_ports clkout]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V10} [get_ports txd]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V11} [get_ports rxd]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V12} [get_ports io3]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V14} [get_ports io4]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN A16} [get_ports resetn]
